### ISSUE TITLE
Anaconda token is expired

### ISSUE THREAD

**Issue by chrisjbillington** [philipstarkey/qtutils#21]
Hi Phil,

I don't have admin access to this repository, and want to make a release. However, this repo has an expired anaconda.org API token. If you could update it to the new token (visible logged into anaconda.org under the labscript-suite org, settings -> access, it's called `github-actions-2021`), or give me whatever rights I need to do it myself, that'd be great!

**Comment by philipstarkey** [comment]
@chrisjbillington 
Should be updated now. I think you'll need to make a dummy commit to retrigger the build. I could retrigger the failed build but it's already gone to test PyPI so I think it'll crash on that step if we retry without a new commit.

**Comment by chrisjbillington** [comment]
Thanks! 

I wanted to make a release anyway, so I'll push a tag. Fairly confident since it did succeed at all the other steps!
